# Generated by Django 5.0.7 on 2024-10-21 03:42

import Concentrado.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('abreviatura', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('estado_documento', models.CharField(choices=[('01_En Revisión', 'En Revisión'), ('02_Con Observaciones', 'Con Observaciones'), ('04_Visto Bueno', 'Visto Bueno')], default='01_En Revisión', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_revision', models.CharField(choices=[('1a_Revisión', 'Primera Revisión'), ('2a_Revisión', 'Segunda Revisión'), ('3a_Revisión', 'Tercera Revisión'), ('4a_Revisión', 'Cuarta Revisión'), ('5a_Revisión', 'Quinta Revisión'), ('6a_Revisión', 'Sexta Revisión')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoControl',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('ruta', models.CharField(choices=[('Control_Extraordinarias', 'Control Extraordinarias'), ('Control_Ordinarias', 'Control Ordinarias'), ('Control_Ordinarias_Especiales', 'Control Ordinarias Especiales'), ('Control_Materiales_Didacticos', 'Control Materiales Didacticos')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ControlMateriales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_documento', models.CharField(max_length=255)),
                ('oficio_recepcion', models.CharField(max_length=255)),
                ('fecha_recepcion', models.DateField()),
                ('oficio_respuesta', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_respuesta', models.DateField(blank=True, null=True)),
                ('documento', models.FileField(upload_to=Concentrado.models.get_document_path, validators=[Concentrado.models.validate_file_extension])),
                ('oficio_llegada', models.FileField(upload_to=Concentrado.models.get_oficio_llegada_path, validators=[Concentrado.models.validate_file_extension])),
                ('oficio_respuesta_archivo', models.FileField(blank=True, null=True, upload_to=Concentrado.models.get_oficio_respuesta_path, validators=[Concentrado.models.validate_file_extension])),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='Concentrado.entidad')),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Concentrado.estatus')),
                ('numero_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='Concentrado.revision')),
                ('tipo_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='Concentrado.tipocontrol')),
            ],
        ),
    ]
